excluded:
  - .build
analyzer_rules:
  - unused_declaration
  - unused_import
opt_in_rules:
  - all
disabled_rules:
  - anonymous_argument_in_multiline_closure
  - balanced_xctest_lifecycle
  - conditional_returns_on_newline
  - contrasted_opening_brace
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_top_level_acl
  - explicit_type_interface
  - file_header
  - inert_defer # Deprecated
  - missing_docs
  - no_extension_access_modifier
  - no_grouping_extension
  - one_declaration_per_file
  - prefer_nimble
  - required_deinit
  - sorted_enum_cases
  - switch_case_on_newline
  - trailing_closure
  - unused_capture_list # Deprecated
  - vertical_whitespace_between_cases
attributes:
  attributes_with_arguments_always_on_line_above: true
  always_on_line_above:
    - "@MainActor"
    - "@Option"
    - "@Suite"
  always_on_same_line:
    - "@ViewBuilder"
    - "@Environment"
    - "@EnvironmentObject"
    - "@Test"
closure_body_length:
    warning: 10
    error: 20
function_body_length: 40
large_tuple: 3
number_separator:
  minimum_length: 5
type_body_length: 300
